version: '3.8'

services:
  nginx:
    build:
      context: ./Nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - service1
      - service2
    networks:
      - mynetwork

  service1:
    build:
      context: . 
      dockerfile: Service1/Dockerfile
    ports:
      - "5001:80"
    networks:
      - mynetwork

  service2:
    build:
      context: .
      dockerfile: Service2/Dockerfile
    ports:
      - "5002:80"
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true
